<?php

namespace Xiaohongyang\LaravelCmsAdmin\DataTable;
use Yajra\DataTables\Contracts\DataTable;
use Yajra\DataTables\DataTables;

/**
 * Created by PhpStorm.
 * User: xiaohongyang 258082291@qq.com
 * Date: 2019/6/2
 * Time: 8:09
 */
class ArticleTypeDataTable extends DataTables
{
//ajra\DataTables\DataTables
    public function getHtmlBuilder()
    {
        return parent::getHtmlBuilder(); // TODO: Change the autogenerated stub
    }

    
}